"use client";
import { useState, useEffect } from "react";
import { Leaf, ChevronRight } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import SimulatedBadge from "@/components/SimulatedBadge";
import { formatLiters, formatCurrency } from "@/lib/utils";

interface Spring { spring_id:number; name:string; village_name:string; current_discharge:number|null; health_score:number|null; }
interface PlanResult { inputs:{targetArea:number;cropType:string;irrigationEfficiency:string;budget:number}; chain:any; optimization:any; rechargeZones:Array<{name:string;priority_rank:number;recharge_suitability_score:number}>; }

export default function FarmPlannerPage(){
 const [springs,setSprings]=useState<Spring[]>([]); const [form,setForm]=useState({springId:"",targetArea:15,cropType:"paddy",irrigationEfficiency:"flood",budget:500000}); const [result,setResult]=useState<PlanResult|null>(null); const [loading,setLoading]=useState(false);
 useEffect(()=>{fetch("/api/springs").then(r=>r.json()).then(d=>{setSprings(d.springs??[]);if(d.springs?.length)setForm(f=>({...f,springId:String(d.springs[0].spring_id)}));});},[]);
 const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();if(!form.springId)return;setLoading(true);try{const r=await fetch("/api/farm-planner",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setResult(await r.json());}finally{setLoading(false);}};
 const crops=[['paddy','Paddy (Rice)'],['wheat','Wheat'],['maize','Maize'],['ragi','Ragi (Finger Millet)'],['vegetables','Vegetables (Mixed)'],['turmeric','Turmeric']]; const irrigation=[['flood','Flood (Conventional)'],['sprinkler','Sprinkler'],['drip','Drip Irrigation']];
 return <div className="space-y-6"><PageHeader icon={Leaf} title="Reverse Farm Planner" subtitle="Work backwards from farm requirements to determine optimal spring revival strategy"/><div className="glass rounded-xl p-5 border border-green-500/20"><div className="flex items-center gap-3 mb-3"><span className="text-green-400 text-2xl">🔄</span><div><h3 className="font-semibold text-white">Reverse Planning Logic</h3><p className="text-xs text-slate-400">Farm Requirement → Water Gap → Spring Improvement → Recharge Strategy</p></div></div><div className="flex items-center gap-2 text-xs flex-wrap">{['Farm Target','Crop Water Req','Water Gap','Spring Improvement','Recharge Strategy'].map((s,i,a)=><div key={s} className="flex items-center gap-2"><span className="bg-green-500/10 border border-green-500/20 text-green-300 px-2 py-1 rounded">{s}</span>{i<a.length-1&&<ChevronRight className="w-3 h-3 text-slate-500"/>}</div>)}</div></div>
 <div className="grid grid-cols-3 gap-4"><div className="glass rounded-xl p-5"><h3 className="font-semibold text-white text-sm mb-4">Planning Parameters</h3><form onSubmit={handleSubmit} className="space-y-4"><label className="text-xs text-slate-400 block">Select Spring<select value={form.springId} onChange={e=>setForm({...form,springId:e.target.value})} className="input-dark text-sm">{springs.map(s=><option key={s.spring_id} value={s.spring_id}>{s.name} ({s.village_name})</option>)}</select></label><label className="text-xs text-slate-400 block">Target Agricultural Area (hectares)<input type="number" min={1} max={200} value={form.targetArea} onChange={e=>setForm({...form,targetArea:+e.target.value})} className="input-dark text-sm"/></label><label className="text-xs text-slate-400 block">Primary Crop<select value={form.cropType} onChange={e=>setForm({...form,cropType:e.target.value})} className="input-dark text-sm">{crops.map(c=><option key={c[0]} value={c[0]}>{c[1]}</option>)}</select></label><label className="text-xs text-slate-400 block">Irrigation Method<select value={form.irrigationEfficiency} onChange={e=>setForm({...form,irrigationEfficiency:e.target.value})} className="input-dark text-sm">{irrigation.map(c=><option key={c[0]} value={c[0]}>{c[1]}</option>)}</select></label><label className="text-xs text-slate-400 block">Available Budget (₹)<input type="number" min={50000} max={5000000} step={50000} value={form.budget} onChange={e=>setForm({...form,budget:+e.target.value})} className="input-dark text-sm"/><span className="text-[11px] text-slate-500">{formatCurrency(form.budget)}</span></label><button type="submit" disabled={loading||!form.springId} className="btn-primary w-full">{loading?'Calculating...':'🔄 Run Reverse Plan'}</button></form></div>
 <div className="col-span-2 space-y-4">{result?<div className="glass rounded-xl p-5"><div className="flex items-center justify-between mb-4"><h3 className="font-semibold text-white">Reverse Planning Chain</h3><SimulatedBadge/></div><div className="grid grid-cols-2 gap-3">{Object.entries(result.chain).map(([k,v])=><div key={k} className="bg-sky-500/5 rounded-lg p-3"><div className="text-[10px] text-slate-500">{k.replaceAll('_',' ')}</div><div className="text-sm font-bold text-white">{typeof v==='number'?Math.round(v as number):String(v)}</div></div>)}</div><div className="mt-5"><h4 className="text-white font-semibold text-sm mb-3">Recommended Interventions</h4><div className="space-y-2">{result.optimization?.selected?.map((x:any)=><div key={x.name} className="flex justify-between bg-sky-500/5 p-3 rounded-lg text-xs"><span className="text-slate-300">{x.name} × {x.units}</span><span className="text-green-300">{formatCurrency(x.cost)}</span></div>)}</div></div></div>:<div className="glass rounded-xl p-16 flex items-center justify-center h-full text-slate-500">Run the reverse planner to generate a spring-to-farm strategy.</div>}</div></div></div>;
}
