"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, BrainCircuit, CheckCircle2, IndianRupee, Target, Zap } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import { formatCurrency, formatLiters } from "@/lib/utils";

type Spring={spring_id:number;name:string;village_name?:string};
export default function OptimizerPage(){
 const [springs,setSprings]=useState<Spring[]>([]); const [result,setResult]=useState<any>(); const [busy,setBusy]=useState(false); const [form,setForm]=useState({springId:"",budget:500000,targetWaterGap:10000});
 useEffect(()=>{fetch("/api/springs").then(r=>r.json()).then(d=>{const s=d.springs??[];setSprings(s);if(s.length)setForm(f=>({...f,springId:String(s[0].spring_id)}))})},[]);
 async function optimize(){setBusy(true);try{const r=await fetch("/api/optimize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setResult(await r.json())}finally{setBusy(false)}}
 const plan=result?.optimization; const selected=plan?.selected??[];
 return <div className="space-y-7"><PageHeader icon={Zap} title="AI Intervention Optimizer" subtitle="Find the strongest recharge package for a spring under a real budget constraint." />
  <div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]">
   <section className="glass glass-strong rounded-2xl p-5"><div className="flex items-center gap-3 mb-5"><div className="rounded-xl bg-amber-400/10 p-2.5"><BrainCircuit className="h-5 w-5 text-amber-300"/></div><div><h2 className="font-bold text-white">Optimization brief</h2><p className="text-xs text-slate-500">Budget + water-gap target</p></div></div><div className="space-y-4"><Field label="Target spring"><select className="input-dark" value={form.springId} onChange={e=>setForm({...form,springId:e.target.value})}>{springs.map(s=><option key={s.spring_id} value={s.spring_id}>{s.name} — {s.village_name??"Village"}</option>)}</select></Field><Field label="Available budget"><input className="input-dark" type="number" value={form.budget} onChange={e=>setForm({...form,budget:+e.target.value})}/></Field><Field label="Target water gap (L/day)"><input className="input-dark" type="number" value={form.targetWaterGap} onChange={e=>setForm({...form,targetWaterGap:+e.target.value})}/></Field><button className="btn-primary w-full flex items-center justify-center gap-2" disabled={busy||!form.springId} onClick={optimize}><Zap className="h-4 w-4"/>{busy?"Optimizing…":"Run AI optimizer"}</button></div><div className="mt-5 rounded-xl border border-amber-400/10 bg-amber-400/[.035] p-4 text-xs leading-5 text-slate-500">The optimizer balances intervention cost, expected recharge and water-gap reduction instead of selecting the cheapest structure alone.</div></section>
   <section className="glass rounded-2xl p-5">{!plan?<div className="flex min-h-[430px] flex-col items-center justify-center text-center"><div className="rounded-2xl border border-amber-400/10 bg-amber-400/5 p-4"><Target className="h-7 w-7 text-amber-300"/></div><h3 className="mt-4 font-bold text-white">Build an intervention package</h3><p className="mt-1 max-w-sm text-sm text-slate-500">Run the optimizer to rank feasible recharge actions against your target gap.</p></div>:<><div className="flex items-start justify-between"><div><div className="text-xs uppercase tracking-[.18em] text-amber-300/70">Recommended package</div><h2 className="mt-2 text-xl font-black text-white">Budget-aware recharge plan</h2></div><span className="badge-green">AI RANKED</span></div><div className="mt-6 grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric icon={IndianRupee} label="Cost" value={formatCurrency(plan.totalCost??0)}/><Metric icon={ArrowUpRight} label="Recharge" value={formatLiters(plan.totalRecharge??0)}/><Metric icon={Target} label="Debt reduction" value={`${plan.waterDebtReduction??0}%`}/><Metric icon={Zap} label="Impact score" value={`${plan.impactScore??0}/100`}/></div><div className="mt-6"><div className="mb-3 flex items-center justify-between"><h3 className="font-semibold text-white">Selected interventions</h3><span className="text-xs text-slate-600">{selected.length} actions</span></div><div className="space-y-2">{selected.map((x:any,i:number)=><div key={`${x.name}-${i}`} className="card-hover flex items-center gap-3 rounded-xl border border-white/5 bg-white/[.025] p-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-emerald-500/10"><CheckCircle2 className="h-4 w-4 text-emerald-300"/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold text-white">{x.name}</div><div className="text-xs text-slate-500">{x.units} unit{x.units===1?"":"s"}</div></div><div className="text-right"><div className="text-sm font-bold text-sky-300">+{formatLiters(x.recharge??0)}</div><div className="text-[10px] text-slate-600">{formatCurrency(x.cost??0)}</div></div></div>)}</div></div><div className="mt-5 flex items-center justify-between rounded-xl border border-sky-400/10 bg-sky-500/[.035] p-4 text-xs text-slate-500"><span>Next: validate spatial suitability before field execution.</span><ArrowUpRight className="h-4 w-4 text-sky-300"/></div></>}</section>
  </div></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs text-slate-400">{label}<div className="mt-1.5">{children}</div></label>}
function Metric({icon:Icon,label,value}:{icon:any;label:string;value:string}){return <div className="rounded-xl border border-white/5 bg-white/[.025] p-3"><Icon className="h-4 w-4 text-sky-300"/><div className="mt-2 text-lg font-black text-white">{value}</div><div className="text-[10px] uppercase tracking-wider text-slate-600">{label}</div></div>}
