"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, CalendarDays, CloudRain, Droplets, Plus, Radio, RefreshCw, Waves } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import { formatNumber } from "@/lib/utils";

type Observation = { observation_id:number; spring_id:number; spring_name?:string|null; date:string; rainfall?:number|null; discharge?:number|null; water_level?:number|null; season?:string|null };
export default function MonitoringPage(){
 const [rows,setRows]=useState<Observation[]>([]); const [loading,setLoading]=useState(true); const [spring,setSpring]=useState("all"); const [refreshing,setRefreshing]=useState(false);
 async function load(){setRefreshing(true);try{const r=await fetch('/api/observations');const d=await r.json();setRows(d.observations??[])}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{load()},[]);
 const springs=useMemo(()=>Array.from(new Map(rows.map(r=>[r.spring_id,r.spring_name??`Spring ${r.spring_id}`])).entries()),[rows]);
 const filtered=spring==='all'?rows:rows.filter(r=>String(r.spring_id)===spring);
 const latest=filtered[0]; const previous=filtered[1];
 const avg=filtered.length?filtered.reduce((s,r)=>s+(r.discharge??0),0)/filtered.length:0;
 const delta=latest?.discharge!=null&&previous?.discharge!=null?latest.discharge-previous.discharge:null;
 return <div className="space-y-7"><PageHeader icon={Activity} title="Field Monitoring" subtitle="Turn community observations into a live spring-health signal." />
  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><span className="badge-green"><Radio className="mr-1 inline h-3 w-3"/> FIELD FEED</span><span className="text-xs text-slate-600">{filtered.length} observations loaded</span></div><div className="flex gap-2"><select className="input-dark min-w-[190px]" value={spring} onChange={e=>setSpring(e.target.value)}><option value="all">All springs</option>{springs.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><button onClick={load} className="btn-secondary flex items-center gap-2" disabled={refreshing}><RefreshCw className={`h-4 w-4 ${refreshing?'animate-spin':''}`}/>Refresh</button></div></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Droplets} label="Latest discharge" value={latest?.discharge==null?'—':`${formatNumber(latest.discharge)} L/day`} note={latest?.date??'No observation'} /><Metric icon={Waves} label="Average discharge" value={`${formatNumber(avg)} L/day`} note="Loaded observation window" /><Metric icon={CloudRain} label="Latest rainfall" value={latest?.rainfall==null?'—':`${formatNumber(latest.rainfall)} mm`} note={latest?.season??'Season not tagged'} /><Metric icon={Activity} label="Trend signal" value={delta==null?'Stable':`${delta>=0?'+':''}${formatNumber(delta)} L/day`} note="vs previous observation" /></div>
  <section className="glass glass-strong rounded-2xl p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-bold text-white">Observation timeline</h2><p className="mt-1 text-xs text-slate-500">Latest field measurements used to validate AI projections.</p></div><span className="badge-blue">COMMUNITY DATA</span></div>{loading?<div className="py-14 text-center text-sm text-slate-500">Loading field observations…</div>:filtered.length?<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-white/5 text-[10px] uppercase tracking-wider text-slate-600"><th className="pb-3">Spring</th><th className="pb-3">Date</th><th className="pb-3">Discharge</th><th className="pb-3">Rainfall</th><th className="pb-3">Water level</th><th className="pb-3">Season</th></tr></thead><tbody>{filtered.map(r=><tr key={r.observation_id} className="border-b border-white/[.035] text-sm"><td className="py-3 font-medium text-white">{r.spring_name??`Spring ${r.spring_id}`}</td><td className="py-3 text-slate-400"><CalendarDays className="mr-1 inline h-3.5 w-3.5"/>{r.date}</td><td className="py-3 font-semibold text-sky-300">{r.discharge==null?'—':`${formatNumber(r.discharge)} L/day`}</td><td className="py-3 text-slate-400">{r.rainfall==null?'—':`${formatNumber(r.rainfall)} mm`}</td><td className="py-3 text-slate-400">{r.water_level==null?'—':formatNumber(r.water_level)}</td><td className="py-3 text-slate-500">{r.season??'—'}</td></tr>)}</tbody></table></div>:<div className="rounded-xl border border-dashed border-white/10 py-14 text-center"><Waves className="mx-auto h-8 w-8 text-slate-600"/><p className="mt-3 text-sm text-slate-500">No field observations available for this filter.</p><p className="mt-1 text-xs text-slate-700">Add measurements through the observation API to activate monitoring.</p></div>}</section>
  <div className="grid gap-4 md:grid-cols-2"><div className="glass rounded-2xl p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-emerald-500/10 p-2.5"><Activity className="h-5 w-5 text-emerald-300"/></div><div><h3 className="font-bold text-white">Validation loop</h3><p className="text-xs text-slate-500">Observe → compare → recalibrate → plan</p></div></div><p className="mt-4 text-sm leading-6 text-slate-400">Monitoring closes the loop between AI projections and real-world spring behavior, making the platform useful beyond a one-time hackathon demo.</p></div><div className="glass rounded-2xl p-5"><div className="flex items-center gap-3"><div className="rounded-xl bg-sky-500/10 p-2.5"><Plus className="h-5 w-5 text-sky-300"/></div><div><h3 className="font-bold text-white">Field-ready workflow</h3><p className="text-xs text-slate-500">Designed for recurring community measurements</p></div></div><p className="mt-4 text-sm leading-6 text-slate-400">Record discharge, rainfall and water-level readings, then use the Simulator and Recharge Map to validate intervention decisions.</p></div></div>
 </div>
}
function Metric({icon:Icon,label,value,note}:{icon:any;label:string;value:string;note:string}){return <div className="glass card-hover rounded-2xl p-5"><div className="flex items-center justify-between"><span className="text-xs font-medium text-slate-500">{label}</span><Icon className="h-4 w-4 text-sky-300"/></div><div className="mt-3 text-2xl font-black text-white">{value}</div><div className="mt-1 text-[11px] text-slate-600">{note}</div></div>}
