"use client";
import { useEffect, useMemo, useState } from "react";
import { GitBranch, Droplets, Sprout, Waves, Home, ShieldCheck, Sparkles, ArrowDown } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import SimulatedBadge from "@/components/SimulatedBadge";

const chain=[
 {title:"Recharge Intervention",desc:"Contour trenches, recharge pits and catchment treatment",icon:Droplets,metric:"Action",tag:"INPUT"},
 {title:"Groundwater Recharge",desc:"Rainwater is slowed, infiltrated and stored in the recharge zone",icon:Waves,metric:"+ recharge",tag:"PROCESS"},
 {title:"Spring Discharge Recovery",desc:"Improved subsurface flow supports the spring source",icon:Sprout,metric:"Spring health",tag:"SIGNAL"},
 {title:"Reliable Water Supply",desc:"More dependable water becomes available for households and farms",icon:Home,metric:"Water security",tag:"OUTCOME"},
 {title:"Protected Agriculture",desc:"Farm water demand is matched with a more resilient supply",icon:Sprout,metric:"Farm support",tag:"OUTCOME"},
 {title:"Community Resilience",desc:"Lower water stress strengthens long-term local resilience",icon:ShieldCheck,metric:"Impact",tag:"IMPACT"}
];
export default function ImpactChainPage(){
 const [springs,setSprings]=useState<any[]>([]); const [id,setId]=useState("");
 useEffect(()=>{fetch("/api/springs").then(r=>r.json()).then(d=>{setSprings(d.springs??[]);if(d.springs?.length)setId(String(d.springs[0].spring_id))}).catch(()=>{});},[]);
 const spring=useMemo(()=>springs.find(s=>String(s.spring_id)===id),[springs,id]); const health=spring?.health_score??0; const discharge=spring?.current_discharge??0;
 return <div className="space-y-6"><PageHeader icon={GitBranch} title="Impact Chain" subtitle="Trace how a recharge decision propagates from landscape intervention to farm and community resilience"/>
  <div className="glass glass-strong rounded-2xl p-5 flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.2em] text-cyan-300">Live planning context</div><h2 className="text-white font-bold mt-1">Spring → Water → Farm → Community</h2><p className="text-xs text-slate-500 mt-1">Select a monitored spring to anchor the impact narrative.</p></div><div className="flex items-center gap-3"><select value={id} onChange={e=>setId(e.target.value)} className="input-dark min-w-[230px]">{springs.map(s=><option key={s.spring_id} value={s.spring_id}>{s.name} — {s.village_name}</option>)}</select><SimulatedBadge/></div></div>
  {spring&&<div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[["Spring health",`${health}/100`],["Current discharge",`${Math.round(discharge).toLocaleString("en-IN")} L/day`],["Village",spring.village_name],["AI state",health>=70?"Stable trajectory":health>=45?"Recovery opportunity":"Priority recovery"]].map(x=><div key={x[0]} className="glass rounded-xl p-4"><div className="text-[10px] uppercase tracking-wider text-slate-500">{x[0]}</div><div className="text-sm font-bold text-white mt-1">{x[1]}</div></div>)}</div>}
  <div className="glass glass-strong rounded-2xl p-6"><div className="flex items-center gap-2 mb-7"><Sparkles className="w-4 h-4 text-cyan-300"/><h3 className="text-white font-semibold">AI causal pathway</h3><span className="text-[10px] text-slate-500 ml-auto">6 linked stages</span></div><div className="max-w-3xl mx-auto">{chain.map((item,i)=>{const Icon=item.icon;return <div key={item.title}><div className="group relative flex items-center gap-4 rounded-2xl border border-white/5 bg-white/[.025] p-4 card-hover"><div className="w-12 h-12 rounded-xl bg-cyan-400/10 border border-cyan-400/15 flex items-center justify-center shrink-0"><Icon className="w-5 h-5 text-cyan-300"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><span className="text-[9px] tracking-[.18em] text-cyan-300">{item.tag}</span><span className="text-[9px] text-slate-600">STAGE {i+1}</span></div><h4 className="text-sm font-bold text-white mt-1">{item.title}</h4><p className="text-xs text-slate-500 mt-1">{item.desc}</p></div><div className="hidden sm:block text-right"><div className="text-[10px] text-slate-500">Signal</div><div className="text-xs font-semibold text-slate-300">{item.metric}</div></div></div>{i<chain.length-1&&<div className="flex flex-col items-center py-1"><div className="h-5 w-px bg-gradient-to-b from-cyan-400/50 to-emerald-400/30"/><ArrowDown className="w-3 h-3 text-cyan-400/60"/></div>}</div>})}</div></div>
  <div className="glass rounded-2xl p-5 border border-emerald-400/10"><div className="flex items-start gap-3"><ShieldCheck className="w-5 h-5 text-emerald-300 mt-0.5"/><div><h3 className="text-white font-semibold text-sm">Why this matters for SIH</h3><p className="text-xs text-slate-400 mt-1">The platform does not stop at identifying a weak spring. It connects landscape action to measurable water recovery, farm protection and community-level outcomes—making the intervention logic explainable to decision makers.</p></div></div></div>
 </div>
}