"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Activity, AlertTriangle, ArrowRight, Database, Droplets, Leaf, RefreshCw, ShieldCheck, TrendingDown, Waves, Zap } from "lucide-react";
import StatCard from "@/components/StatCard";
import { formatLiters, getClassificationColor, getClassificationLabel } from "@/lib/utils";

export default function DashboardPage() {
  const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [seeding, setSeeding] = useState(false);
  const load = async () => { setLoading(true); try { const r = await fetch("/api/dashboard"); const j = await r.json(); if (j.error) throw new Error(j.error); setData(j); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load dashboard"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const seed = async () => { setSeeding(true); try { await fetch("/api/seed", { method: "POST" }); await load(); } finally { setSeeding(false); } };
  if (loading) return <div className="flex min-h-[70vh] items-center justify-center"><div className="text-center"><div className="mx-auto mb-5 flex h-20 w-20 items-center justify-center rounded-full border border-sky-400/20 bg-sky-400/5 shadow-[0_0_60px_rgba(14,165,233,.15)]"><Waves className="h-8 w-8 animate-pulse text-sky-400" /></div><p className="text-sm font-bold tracking-[.25em] text-sky-300">JALCHAKRA AI</p><p className="mt-2 text-xs text-slate-500">Synchronising water intelligence…</p></div></div>;
  if (!data) return <div className="glass rounded-3xl p-10 text-center"><AlertTriangle className="mx-auto mb-4 h-10 w-10 text-orange-400" /><h2 className="text-lg font-bold">Demo intelligence is offline</h2><p className="mx-auto mt-2 max-w-md text-sm text-slate-500">{error || "Seed the prototype dataset to explore the dashboard."}</p><button onClick={seed} className="btn-primary mx-auto mt-6 inline-flex items-center gap-2"><Database className="h-4 w-4" />{seeding ? "Seeding…" : "Seed Demo Data"}</button></div>;
  const s = data.stats; const springs = data.springs ?? []; const alerts = data.alerts ?? []; const risk = s.springsAtRisk || 0;
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-3xl border border-sky-400/20 bg-gradient-to-br from-sky-500/[.12] via-cyan-500/[.04] to-transparent p-6 shadow-[0_0_50px_rgba(14,165,233,.06)]">
      <div className="absolute -right-16 -top-20 h-56 w-56 rounded-full bg-cyan-400/10 blur-3xl" />
      <div className="relative flex flex-col justify-between gap-5 lg:flex-row lg:items-center"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.18em] text-emerald-300"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400" />Live intelligence</div><h1 className="text-3xl font-black text-white">Water Intelligence <span className="gradient-text">Command Center</span></h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Monitor spring health, detect water stress, and turn recharge intelligence into farm-level action.</p></div><div className="flex gap-2"><span className="badge-blue rounded-full px-3 py-2 text-xs">Prototype Data</span><button onClick={load} className="btn-primary inline-flex items-center gap-2 text-sm"><RefreshCw className="h-4 w-4" />Refresh</button></div></div>
    </section>
    <div className="grid grid-cols-2 gap-4 xl:grid-cols-4"><StatCard title="Active Springs" value={s.totalSprings} subtitle={`${s.totalVillages} villages monitored`} icon={Waves} iconColor="text-sky-400" iconBg="from-sky-500/25 to-cyan-500/10" accentColor="#0ea5e9" badge="LIVE" badgeColor="badge-green" /><StatCard title="Water Availability" value={formatLiters(s.totalDischarge)} subtitle="Combined current discharge" icon={Droplets} iconColor="text-cyan-400" iconBg="from-cyan-500/25 to-teal-500/10" accentColor="#06b6d4" /><StatCard title="Springs at Risk" value={risk} subtitle="Declining or critical" icon={AlertTriangle} iconColor="text-orange-400" iconBg="from-orange-500/25 to-red-500/10" accentColor="#f97316" /><StatCard title="Spring Health" value={`${s.avgHealthScore}/100`} subtitle="Average health score" icon={Activity} iconColor="text-emerald-400" iconBg="from-emerald-500/25 to-green-500/10" accentColor="#10b981" /></div>
    <div className="grid gap-4 lg:grid-cols-3"><section className="glass rounded-3xl p-5 lg:col-span-2"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold text-white">Spring → Farm Intelligence</h2><p className="text-xs text-slate-500">The decision chain powering JALCHAKRA AI</p></div><span className="badge-blue rounded-full px-2.5 py-1 text-[10px]">AI PIPELINE</span></div><div className="grid gap-3 md:grid-cols-4">{[[Waves,"Spring DNA","Health & discharge","/spring-dna"],[Droplets,"Recharge Map","Zones & interventions","/recharge-map"],[TrendingDown,"Water Debt","Demand vs supply","/water-debt"],[Leaf,"Farm Planner","Crop decisions","/farm-planner"]].map(([Icon,title,sub,href]: any,i)=><Link href={href} key={title} className="group rounded-2xl border border-sky-500/10 bg-white/[.02] p-4 transition hover:-translate-y-1 hover:border-sky-400/30 hover:bg-sky-400/[.05]"><div className="mb-4 flex items-center justify-between"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-sky-400/10 text-sky-300"><Icon className="h-4 w-4" /></div><ArrowRight className="h-4 w-4 text-slate-700 transition group-hover:translate-x-1 group-hover:text-sky-300" /></div><p className="text-sm font-bold text-slate-200">{title}</p><p className="mt-1 text-[11px] text-slate-500">{sub}</p><div className="mt-4 h-1 overflow-hidden rounded-full bg-slate-800"><div className="h-full w-2/3 rounded-full bg-gradient-to-r from-sky-500 to-cyan-300" /></div></Link>)}</div></section><section className="glass rounded-3xl p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold text-white">AI Alerts</h2><p className="text-xs text-slate-500">Priority signals</p></div><Zap className="h-4 w-4 text-yellow-300" /></div><div className="space-y-3">{alerts.slice(0,4).map((a:any)=><div key={a.alert_id} className="rounded-xl border border-orange-400/15 bg-orange-400/[.04] p-3"><p className="text-xs leading-relaxed text-slate-300">{a.message}</p></div>)}{alerts.length===0&&<p className="text-sm text-slate-500">No active alerts.</p>}</div></section></div>
    <section className="glass rounded-3xl p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-white">Spring Health Snapshot</h2><p className="text-xs text-slate-500">Highest-priority springs for field attention</p></div><Link href="/spring-dna" className="text-xs text-sky-300 hover:text-sky-200">View all →</Link></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{springs.slice(0,8).map((x:any)=><Link href={`/spring-dna/${x.spring_id}`} key={x.spring_id} className="rounded-2xl border border-white/5 bg-white/[.02] p-4 transition hover:border-sky-400/20 hover:bg-sky-400/[.04]"><div className="flex items-center justify-between"><span className="text-[10px] font-bold tracking-widest text-slate-600">S-{String(x.spring_id).padStart(3,"0")}</span><span className="rounded-full px-2 py-1 text-[10px] font-semibold" style={{color:getClassificationColor(x.classification??"green"),background:`${getClassificationColor(x.classification??"green")}15`}}>{getClassificationLabel(x.classification??"green")}</span></div><p className="mt-3 truncate text-sm font-bold text-slate-200">{x.name}</p><div className="mt-3 flex items-end justify-between"><span className="text-2xl font-black" style={{color:getClassificationColor(x.classification??"green")}}>{x.health_score ?? "—"}</span><span className="text-[10px] text-slate-500">/100 health</span></div></Link>)}</div></section>
    <div className="grid grid-cols-2 gap-4 md:grid-cols-4"><div className="glass rounded-2xl p-4"><ShieldCheck className="h-5 w-5 text-emerald-400"/><p className="mt-3 text-2xl font-black">{s.totalFarms}</p><p className="text-xs text-slate-500">Farms monitored</p></div><div className="glass rounded-2xl p-4"><Leaf className="h-5 w-5 text-lime-400"/><p className="mt-3 text-2xl font-black">{s.agriArea} ha</p><p className="text-xs text-slate-500">Agricultural area</p></div><div className="glass rounded-2xl p-4"><TrendingDown className="h-5 w-5 text-red-400"/><p className="mt-3 text-2xl font-black">{formatLiters(s.waterDebt)}</p><p className="text-xs text-slate-500">Current water debt</p></div><div className="glass rounded-2xl p-4"><Waves className="h-5 w-5 text-sky-400"/><p className="mt-3 text-2xl font-black">{s.totalVillages}</p><p className="text-xs text-slate-500">Villages connected</p></div></div>
  </div>;
}
