"use client";
import { useEffect, useState } from "react";
import { BrainCircuit, CloudRain, Play, Sparkles, TrendingUp } from "lucide-react";
import PageHeader from "@/components/PageHeader";
import { formatLiters, formatNumber } from "@/lib/utils";

type Spring={spring_id:number;name:string;village_name?:string};
type Result={results?:any;springName?:string;error?:string};
export default function SimulatorPage(){
 const [springs,setSprings]=useState<Spring[]>([]); const [springId,setSpringId]=useState(""); const [years,setYears]=useState(5); const [budget,setBudget]=useState(500000); const [rainfall,setRainfall]=useState("normal"); const [scenario,setScenario]=useState("combined"); const [result,setResult]=useState<Result|null>(null); const [busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/springs").then(r=>r.json()).then(d=>{const s=d.springs??[];setSprings(s);if(s.length)setSpringId(String(s[0].spring_id))})},[]);
 async function run(){if(!springId)return;setBusy(true);setResult(null);try{const r=await fetch("/api/simulate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({springId,years,budget,rainfallScenario:rainfall,scenario})});setResult(await r.json())}finally{setBusy(false)}}
 const values=result?.results??{}; const entries=Object.entries(values).filter(([,v])=>typeof v==="number") as [string,number][];
 return <div className="space-y-7"><PageHeader icon={TrendingUp} title="Future Water Simulator" subtitle="Stress-test spring revival plans before field deployment." />
  <div className="grid gap-5 xl:grid-cols-[.72fr_1.28fr]">
   <section className="glass glass-strong rounded-2xl p-5"><div className="mb-5 flex items-center gap-3"><div className="rounded-xl bg-violet-500/10 p-2.5"><BrainCircuit className="h-5 w-5 text-violet-300"/></div><div><h2 className="font-bold text-white">Scenario controls</h2><p className="text-xs text-slate-500">Tune the assumptions fed to the model.</p></div></div>
    <div className="space-y-4"><Field label="Target spring"><select className="input-dark" value={springId} onChange={e=>setSpringId(e.target.value)}>{springs.map(s=><option key={s.spring_id} value={s.spring_id}>{s.name} — {s.village_name??"Village"}</option>)}</select></Field><Field label="Intervention scenario"><select className="input-dark" value={scenario} onChange={e=>setScenario(e.target.value)}><option value="combined">Combined revival</option><option value="recharge_only">Recharge only</option><option value="farm_only">Farm planning only</option><option value="do_nothing">Do nothing</option></select></Field><div className="grid grid-cols-2 gap-3"><Field label="Horizon (years)"><input className="input-dark" type="number" min="1" max="20" value={years} onChange={e=>setYears(+e.target.value)}/></Field><Field label="Budget (₹)"><input className="input-dark" type="number" min="0" value={budget} onChange={e=>setBudget(+e.target.value)}/></Field></div><Field label="Rainfall assumption"><select className="input-dark" value={rainfall} onChange={e=>setRainfall(e.target.value)}><option value="normal">Normal</option><option value="good">Above normal</option><option value="poor">Below normal</option><option value="extreme">Extreme variability</option></select></Field><button onClick={run} disabled={busy||!springId} className="btn-primary w-full flex items-center justify-center gap-2 disabled:opacity-50"><Play className="h-4 w-4"/>{busy?"Running model…":"Run AI simulation"}</button></div>
   </section>
   <section className="glass rounded-2xl p-5 min-h-[430px]">{result?.error?<div className="rounded-xl border border-rose-400/10 bg-rose-500/5 p-5 text-sm text-rose-200">Simulation error: {result.error}</div>:result?<><div className="flex items-start justify-between"><div><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-amber-300"/><span className="text-xs uppercase tracking-[.18em] text-amber-300/70">AI projection</span></div><h2 className="mt-2 text-xl font-black text-white">{result.springName??"Selected spring"}</h2><p className="text-xs text-slate-500">{scenario.replaceAll("_"," ")} · {years} year horizon · {rainfall} rainfall</p></div><span className="badge-green">SIMULATED</span></div><div className="mt-6 grid gap-3 sm:grid-cols-2">{entries.slice(0,6).map(([key,val])=><div key={key} className="rounded-xl border border-white/5 bg-white/[.025] p-4"><div className="text-[10px] uppercase tracking-wider text-slate-600">{key.replaceAll("_"," ")}</div><div className="mt-2 text-xl font-black text-white">{key.toLowerCase().includes("water")||key.toLowerCase().includes("recharge")||key.toLowerCase().includes("discharge")?formatLiters(val):formatNumber(val)}</div><div className="mt-3 h-1 overflow-hidden rounded-full bg-white/5"><div className="h-full bg-gradient-to-r from-violet-500 to-sky-400" style={{width:`${Math.min(100,Math.max(8,Math.abs(val)%101))}%`}}/></div></div>)}</div><div className="mt-5 rounded-xl border border-violet-400/10 bg-violet-500/[.04] p-4 text-sm leading-6 text-slate-400"><CloudRain className="mr-2 inline h-4 w-4 text-violet-300"/>Use this scenario to compare assumptions, then validate the recommended intervention through the Optimizer and Recharge Map.</div></>:<div className="flex h-full min-h-[380px] flex-col items-center justify-center text-center"><div className="rounded-2xl border border-violet-400/10 bg-violet-500/5 p-4"><TrendingUp className="h-7 w-7 text-violet-300"/></div><h3 className="mt-4 font-bold text-white">No projection yet</h3><p className="mt-1 max-w-sm text-sm text-slate-500">Select a spring, tune the assumptions and run the model to reveal future water signals.</p></div>}</section>
  </div></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-xs text-slate-400">{label}<div className="mt-1.5">{children}</div></label>}
